DASHSCOPE_API_KEY="sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
OPENAI_API_KEY = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
APPCODE_TYP = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
APPCODE_KEY = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

NEO4J_ADDR="xxx.xxx.xxx.xxx"
NEO4J_PORT="xxxxx"
NEO4J_USER="xxxxx"
NEO4J_PASS="xxxxx"

BASE_URL = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
MORE_URL = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
OPEN_URL = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

DEEP_URL = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"