DASHSCOPE_API_KEY="sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
APPCODE_KEY = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

NEO4J_ADDR="xxx.xxx.xxx.xxx"
NEO4J_PORT="xxxxx"
NEO4J_USER="xxxxx"
NEO4J_PASS="xxxxx"

DEEP_URL = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
DASH_URL = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
BGEM_URL = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"